"""Retrieval evaluation framework using auto-calibrated ground truth.

Uses the baseline generated by calibrate.py (outputs/eval_baseline.json)
instead of manually specified expected chunks.

Usage:
    # First generate baseline (one-time):
    python -m app.calibrate --mode baseline

    # Then evaluate:
    python main.py eval                        # compare dense vs hybrid
    python -m app.evaluate --mode hybrid       # evaluate single mode
    python -m app.evaluate --mode compare      # side-by-side comparison
"""

import json
import time
import logging
from pathlib import Path
from typing import List, Dict, Any
from dataclasses import dataclass, field, asdict

from app.config import settings
from app.calibrate import MODULE_QUERIES, BASELINE_FILE, load_baseline

logger = logging.getLogger(__name__)


@dataclass
class TestResult:
    """Result of a single evaluation test case."""
    name: str
    query: str
    overlap_pct: float       # Fraction of baseline chunks still retrieved
    source_coverage: float   # Fraction of baseline sources found
    new_chunks: int          # Chunks found that weren't in baseline
    missing_chunks: int      # Baseline chunks not found
    retrieved_count: int
    baseline_count: int
    retrieval_time_ms: float
    top_sources: List[str] = field(default_factory=list)


@dataclass
class EvalReport:
    """Aggregate evaluation report."""
    mode: str
    total_tests: int
    avg_overlap: float
    avg_source_coverage: float
    avg_new_chunks: float
    avg_missing_chunks: float
    avg_retrieval_time_ms: float
    test_results: List[Dict] = field(default_factory=list)


class RetrievalEvaluator:
    """Evaluates retrieval quality against auto-calibrated baseline."""

    def __init__(self):
        self._retriever = None
        self._baseline = None

    def load_retriever(self, mode: str = "hybrid", enable_reranker: bool = True):
        """Load the retriever in specified mode."""
        from app.hybrid_retriever import HybridRetriever

        self._retriever = HybridRetriever()
        self._retriever.load(mode=mode, enable_reranker=enable_reranker)
        logger.info(f"Evaluator loaded retriever in mode={mode}")

    def load_baseline(self):
        """Load calibration baseline."""
        self._baseline = load_baseline()
        logger.info(f"Baseline loaded (created: {self._baseline['created_at']}, mode: {self._baseline['mode']})")

    def evaluate_single(self, module_name: str) -> TestResult:
        """Run evaluation on a single module against baseline."""
        if self._baseline is None:
            raise RuntimeError("No baseline loaded. Run: python -m app.calibrate --mode baseline")

        bl = self._baseline["modules"].get(module_name)
        if bl is None:
            raise ValueError(f"Module '{module_name}' not found in baseline")

        config = MODULE_QUERIES.get(module_name)
        if config is None:
            raise ValueError(f"Module '{module_name}' not found in MODULE_QUERIES")

        # Run retrieval
        result = self._retriever.retrieve(
            query=config["query"],
            k_rtl=config["k_rtl"],
            rerank=True,
        )
        docs = result["documents"]
        metadata = result["metadata"]

        # Compare against baseline
        retrieved_chunks = set(d.metadata.get("chunk_id", "") for d in docs)
        baseline_chunks = set(bl["chunk_ids"])

        overlap = retrieved_chunks & baseline_chunks
        missing = baseline_chunks - retrieved_chunks
        new = retrieved_chunks - baseline_chunks

        overlap_pct = len(overlap) / len(baseline_chunks) if baseline_chunks else 0

        # Source coverage
        retrieved_sources = set(Path(d.metadata.get("source", "")).name for d in docs)
        baseline_sources = set(bl["sources"])
        sources_found = len(retrieved_sources & baseline_sources)
        source_coverage = sources_found / len(baseline_sources) if baseline_sources else 0

        return TestResult(
            name=module_name,
            query=config["query"][:80] + "...",
            overlap_pct=round(overlap_pct, 4),
            source_coverage=round(source_coverage, 4),
            new_chunks=len(new),
            missing_chunks=len(missing),
            retrieved_count=len(retrieved_chunks),
            baseline_count=len(baseline_chunks),
            retrieval_time_ms=metadata.get("total_retrieval_time_ms", 0),
            top_sources=list(retrieved_sources)[:5],
        )

    def evaluate_all(self) -> EvalReport:
        """Run evaluation across all modules."""
        if self._baseline is None:
            self.load_baseline()

        results = []
        for module_name in MODULE_QUERIES:
            if module_name not in self._baseline["modules"]:
                logger.warning(f"Skipping {module_name} — not in baseline")
                continue

            logger.info(f"Evaluating: {module_name}")
            result = self.evaluate_single(module_name)
            results.append(result)

            status = "✅" if result.overlap_pct >= 0.7 else "⚠️" if result.overlap_pct >= 0.4 else "❌"
            logger.info(
                f"  {status} {result.name}: overlap={result.overlap_pct:.0%} "
                f"(+{result.new_chunks} new, -{result.missing_chunks} lost) "
                f"{result.retrieval_time_ms:.0f}ms"
            )

        n = len(results)
        report = EvalReport(
            mode=self._retriever._mode if self._retriever else "unknown",
            total_tests=n,
            avg_overlap=round(sum(r.overlap_pct for r in results) / n, 4) if n else 0,
            avg_source_coverage=round(sum(r.source_coverage for r in results) / n, 4) if n else 0,
            avg_new_chunks=round(sum(r.new_chunks for r in results) / n, 2) if n else 0,
            avg_missing_chunks=round(sum(r.missing_chunks for r in results) / n, 2) if n else 0,
            avg_retrieval_time_ms=round(sum(r.retrieval_time_ms for r in results) / n, 2) if n else 0,
            test_results=[asdict(r) for r in results],
        )

        return report

    def compare_modes(self) -> Dict[str, Any]:
        """Compare dense-only vs hybrid retrieval against baseline."""
        self.load_baseline()
        comparison = {}

        # Dense only
        logger.info("=" * 60)
        logger.info("Evaluating: DENSE ONLY (FAISS)")
        logger.info("=" * 60)
        self.load_retriever(mode="dense_only", enable_reranker=False)
        dense_report = self.evaluate_all()
        comparison["dense_only"] = asdict(dense_report)

        # Hybrid
        logger.info("=" * 60)
        logger.info("Evaluating: HYBRID (FAISS + BM25 + Reranker)")
        logger.info("=" * 60)
        self.load_retriever(mode="hybrid", enable_reranker=True)
        hybrid_report = self.evaluate_all()
        comparison["hybrid"] = asdict(hybrid_report)

        # Summary
        comparison["summary"] = {
            "overlap_improvement": round(
                hybrid_report.avg_overlap - dense_report.avg_overlap, 4
            ),
            "source_coverage_improvement": round(
                hybrid_report.avg_source_coverage - dense_report.avg_source_coverage, 4
            ),
        }

        return comparison


def print_report(report: EvalReport):
    """Pretty-print a single evaluation report."""
    print(f"\n{'─' * 55}")
    print(f"  {report.mode.upper()}")
    print(f"{'─' * 55}")
    print(f"  Baseline Overlap:  {report.avg_overlap:.2%}")
    print(f"  Source Coverage:   {report.avg_source_coverage:.2%}")
    print(f"  Avg New Chunks:    +{report.avg_new_chunks:.1f}")
    print(f"  Avg Missing:       -{report.avg_missing_chunks:.1f}")
    print(f"  Avg Latency:       {report.avg_retrieval_time_ms:.0f}ms")

    print(f"\n  Per module:")
    for r in report.test_results:
        status = "✅" if r["overlap_pct"] >= 0.7 else "⚠️" if r["overlap_pct"] >= 0.4 else "❌"
        print(
            f"    {status} {r['name']:25s} | overlap: {r['overlap_pct']:5.0%} "
            f"({r['retrieved_count']}/{r['baseline_count']}) "
            f"| +{r['new_chunks']} new | -{r['missing_chunks']} lost"
        )


def print_comparison(comparison: Dict):
    """Pretty-print comparison results."""
    print(f"\n{'=' * 65}")
    print("RETRIEVAL EVALUATION — DENSE vs HYBRID (vs Baseline)")
    print(f"{'=' * 65}")

    for mode_name, key in [("Dense Only (FAISS)", "dense_only"), ("Hybrid (FAISS+BM25+Reranker)", "hybrid")]:
        r = comparison[key]
        print(f"\n{'─' * 55}")
        print(f"  {mode_name}")
        print(f"{'─' * 55}")
        print(f"  Baseline Overlap:  {r['avg_overlap']:.2%}")
        print(f"  Source Coverage:   {r['avg_source_coverage']:.2%}")
        print(f"  Avg New Chunks:    +{r['avg_new_chunks']:.1f}")
        print(f"  Avg Missing:       -{r['avg_missing_chunks']:.1f}")
        print(f"  Avg Latency:       {r['avg_retrieval_time_ms']:.0f}ms")

    s = comparison["summary"]
    print(f"\n{'─' * 55}")
    print(f"  IMPROVEMENT (Hybrid over Dense)")
    print(f"{'─' * 55}")
    print(f"  Overlap:           {s['overlap_improvement']:+.2%}")
    print(f"  Source Coverage:   {s['source_coverage_improvement']:+.2%}")
    print(f"{'=' * 65}")


def save_report(data: Dict, filepath: str = "outputs/eval_report.json"):
    """Save evaluation report to JSON."""
    Path(filepath).parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w") as f:
        json.dump(data, f, indent=2)
    logger.info(f"Report saved to {filepath}")


if __name__ == "__main__":
    import argparse

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    )

    parser = argparse.ArgumentParser(description="Evaluate retrieval quality")
    parser.add_argument(
        "--mode",
        choices=["dense_only", "hybrid", "compare"],
        default="compare",
        help="Evaluation mode",
    )
    args = parser.parse_args()

    evaluator = RetrievalEvaluator()

    if args.mode == "compare":
        comparison = evaluator.compare_modes()
        print_comparison(comparison)
        save_report(comparison)
    else:
        evaluator.load_baseline()
        evaluator.load_retriever(
            mode=args.mode,
            enable_reranker=(args.mode == "hybrid"),
        )
        report = evaluator.evaluate_all()
        print_report(report)
        save_report(asdict(report))
